CREATE TABLE Account( AccountID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,AccountNAME VARCHAR(30) NOT NULL,AccountADDRESS VARCHAR(30) NOT NULL,AccountCITY VARCHAR(30) NOT NULL,AccountSTATE VARCHAR(30) NOT NULL,AccountCOUNTRY VARCHAR(30) NOT NULL,AccountZIPCODE VARCHAR(30) NOT NULL)

