CREATE TABLE Administration( AdministrationID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,AdministrationNAME VARCHAR(30) NOT NULL,AdministrationADDRESS VARCHAR(30) NOT NULL,AdministrationCITY VARCHAR(30) NOT NULL,AdministrationSTATE VARCHAR(30) NOT NULL,AdministrationCOUNTRY VARCHAR(30) NOT NULL,AdministrationZIPCODE VARCHAR(30) NOT NULL)

