CREATE TABLE Agency( AgencyID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,AgencyNAME VARCHAR(30) NOT NULL,AgencyADDRESS VARCHAR(30) NOT NULL,AgencyCITY VARCHAR(30) NOT NULL,AgencySTATE VARCHAR(30) NOT NULL,AgencyCOUNTRY VARCHAR(30) NOT NULL,AgencyZIPCODE VARCHAR(30) NOT NULL)

