CREATE TABLE Amenity( AmenityID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,AmenityNAME VARCHAR(30) NOT NULL,AmenityADDRESS VARCHAR(30) NOT NULL,AmenityCITY VARCHAR(30) NOT NULL,AmenitySTATE VARCHAR(30) NOT NULL,AmenityCOUNTRY VARCHAR(30) NOT NULL,AmenityZIPCODE VARCHAR(30) NOT NULL)

