CREATE TABLE AppartmentSecurity( AppartmentSecurityID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,AppartmentSecurityNAME VARCHAR(30) NOT NULL,AppartmentSecurityADDRESS VARCHAR(30) NOT NULL,AppartmentSecurityCITY VARCHAR(30) NOT NULL,AppartmentSecuritySTATE VARCHAR(30) NOT NULL,AppartmentSecurityCOUNTRY VARCHAR(30) NOT NULL,AppartmentSecurityZIPCODE VARCHAR(30) NOT NULL)

