CREATE TABLE AppartmentAccessory( AppartmentAccessoryID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,AppartmentAccessoryNAME VARCHAR(30) NOT NULL,AppartmentAccessoryADDRESS VARCHAR(30) NOT NULL,AppartmentAccessoryCITY VARCHAR(30) NOT NULL,AppartmentAccessorySTATE VARCHAR(30) NOT NULL,AppartmentAccessoryCOUNTRY VARCHAR(30) NOT NULL,AppartmentAccessoryZIPCODE VARCHAR(30) NOT NULL)

