CREATE TABLE ApparmentBlock( ApparmentBlockID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,ApparmentBlockNAME VARCHAR(30) NOT NULL,ApparmentBlockADDRESS VARCHAR(30) NOT NULL,ApparmentBlockCITY VARCHAR(30) NOT NULL,ApparmentBlockSTATE VARCHAR(30) NOT NULL,ApparmentBlockCOUNTRY VARCHAR(30) NOT NULL,ApparmentBlockZIPCODE VARCHAR(30) NOT NULL)

