CREATE TABLE Appartment( AppartmentID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,AppartmentNAME VARCHAR(30) NOT NULL,AppartmentADDRESS VARCHAR(30) NOT NULL,AppartmentCITY VARCHAR(30) NOT NULL,AppartmentSTATE VARCHAR(30) NOT NULL,AppartmentCOUNTRY VARCHAR(30) NOT NULL,AppartmentZIPCODE VARCHAR(30) NOT NULL)

