CREATE TABLE Appointment( AppointmentID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,AppointmentNAME VARCHAR(30) NOT NULL,AppointmentADDRESS VARCHAR(30) NOT NULL,AppointmentCITY VARCHAR(30) NOT NULL,AppointmentSTATE VARCHAR(30) NOT NULL,AppointmentCOUNTRY VARCHAR(30) NOT NULL,AppointmentZIPCODE VARCHAR(30) NOT NULL)

