CREATE TABLE Architect( ArchitectID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,ArchitectNAME VARCHAR(30) NOT NULL,ArchitectADDRESS VARCHAR(30) NOT NULL,ArchitectCITY VARCHAR(30) NOT NULL,ArchitectSTATE VARCHAR(30) NOT NULL,ArchitectCOUNTRY VARCHAR(30) NOT NULL,ArchitectZIPCODE VARCHAR(30) NOT NULL)

