CREATE TABLE Area( AreaID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,AreaNAME VARCHAR(30) NOT NULL,AreaADDRESS VARCHAR(30) NOT NULL,AreaCITY VARCHAR(30) NOT NULL,AreaSTATE VARCHAR(30) NOT NULL,AreaCOUNTRY VARCHAR(30) NOT NULL,AreaZIPCODE VARCHAR(30) NOT NULL)

