CREATE TABLE Asset( AssetID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,AssetNAME VARCHAR(30) NOT NULL,AssetADDRESS VARCHAR(30) NOT NULL,AssetCITY VARCHAR(30) NOT NULL,AssetSTATE VARCHAR(30) NOT NULL,AssetCOUNTRY VARCHAR(30) NOT NULL,AssetZIPCODE VARCHAR(30) NOT NULL)

