CREATE TABLE Attachment( AttachmentID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,AttachmentNAME VARCHAR(30) NOT NULL,AttachmentADDRESS VARCHAR(30) NOT NULL,AttachmentCITY VARCHAR(30) NOT NULL,AttachmentSTATE VARCHAR(30) NOT NULL,AttachmentCOUNTRY VARCHAR(30) NOT NULL,AttachmentZIPCODE VARCHAR(30) NOT NULL)

