CREATE TABLE Attending( AttendingID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,AttendingNAME VARCHAR(30) NOT NULL,AttendingADDRESS VARCHAR(30) NOT NULL,AttendingCITY VARCHAR(30) NOT NULL,AttendingSTATE VARCHAR(30) NOT NULL,AttendingCOUNTRY VARCHAR(30) NOT NULL,AttendingZIPCODE VARCHAR(30) NOT NULL)

