CREATE TABLE Beneficiary( BeneficiaryID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,BeneficiaryNAME VARCHAR(30) NOT NULL,BeneficiaryADDRESS VARCHAR(30) NOT NULL,BeneficiaryCITY VARCHAR(30) NOT NULL,BeneficiarySTATE VARCHAR(30) NOT NULL,BeneficiaryCOUNTRY VARCHAR(30) NOT NULL,BeneficiaryZIPCODE VARCHAR(30) NOT NULL)

