CREATE TABLE Blog( BlogID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,BlogNAME VARCHAR(30) NOT NULL,BlogADDRESS VARCHAR(30) NOT NULL,BlogCITY VARCHAR(30) NOT NULL,BlogSTATE VARCHAR(30) NOT NULL,BlogCOUNTRY VARCHAR(30) NOT NULL,BlogZIPCODE VARCHAR(30) NOT NULL)

