CREATE TABLE Booking( BookingID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,BookingNAME VARCHAR(30) NOT NULL,BookingADDRESS VARCHAR(30) NOT NULL,BookingCITY VARCHAR(30) NOT NULL,BookingSTATE VARCHAR(30) NOT NULL,BookingCOUNTRY VARCHAR(30) NOT NULL,BookingZIPCODE VARCHAR(30) NOT NULL)

