CREATE TABLE Braintree( BraintreeID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,BraintreeNAME VARCHAR(30) NOT NULL,BraintreeADDRESS VARCHAR(30) NOT NULL,BraintreeCITY VARCHAR(30) NOT NULL,BraintreeSTATE VARCHAR(30) NOT NULL,BraintreeCOUNTRY VARCHAR(30) NOT NULL,BraintreeZIPCODE VARCHAR(30) NOT NULL)

