CREATE TABLE Careteam( CareteamID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,CareteamNAME VARCHAR(30) NOT NULL,CareteamADDRESS VARCHAR(30) NOT NULL,CareteamCITY VARCHAR(30) NOT NULL,CareteamSTATE VARCHAR(30) NOT NULL,CareteamCOUNTRY VARCHAR(30) NOT NULL,CareteamZIPCODE VARCHAR(30) NOT NULL)

