CREATE TABLE Checkingaccount( CheckingaccountID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,CheckingaccountNAME VARCHAR(30) NOT NULL,CheckingaccountADDRESS VARCHAR(30) NOT NULL,CheckingaccountCITY VARCHAR(30) NOT NULL,CheckingaccountSTATE VARCHAR(30) NOT NULL,CheckingaccountCOUNTRY VARCHAR(30) NOT NULL,CheckingaccountZIPCODE VARCHAR(30) NOT NULL)

