CREATE TABLE Claim( ClaimID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,ClaimNAME VARCHAR(30) NOT NULL,ClaimADDRESS VARCHAR(30) NOT NULL,ClaimCITY VARCHAR(30) NOT NULL,ClaimSTATE VARCHAR(30) NOT NULL,ClaimCOUNTRY VARCHAR(30) NOT NULL,ClaimZIPCODE VARCHAR(30) NOT NULL)

