CREATE TABLE Clinic( ClinicID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,ClinicNAME VARCHAR(30) NOT NULL,ClinicADDRESS VARCHAR(30) NOT NULL,ClinicCITY VARCHAR(30) NOT NULL,ClinicSTATE VARCHAR(30) NOT NULL,ClinicCOUNTRY VARCHAR(30) NOT NULL,ClinicZIPCODE VARCHAR(30) NOT NULL)

