CREATE TABLE Club( ClubID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,ClubNAME VARCHAR(30) NOT NULL,ClubADDRESS VARCHAR(30) NOT NULL,ClubCITY VARCHAR(30) NOT NULL,ClubSTATE VARCHAR(30) NOT NULL,ClubCOUNTRY VARCHAR(30) NOT NULL,ClubZIPCODE VARCHAR(30) NOT NULL)

