CREATE TABLE Company( CompanyID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,CompanyNAME VARCHAR(30) NOT NULL,CompanyADDRESS VARCHAR(30) NOT NULL,CompanyCITY VARCHAR(30) NOT NULL,CompanySTATE VARCHAR(30) NOT NULL,CompanyCOUNTRY VARCHAR(30) NOT NULL,CompanyZIPCODE VARCHAR(30) NOT NULL)

