CREATE TABLE Contest( ContestID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,ContestNAME VARCHAR(30) NOT NULL,ContestADDRESS VARCHAR(30) NOT NULL,ContestCITY VARCHAR(30) NOT NULL,ContestSTATE VARCHAR(30) NOT NULL,ContestCOUNTRY VARCHAR(30) NOT NULL,ContestZIPCODE VARCHAR(30) NOT NULL)

