CREATE TABLE Corporation( CorporationID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,CorporationNAME VARCHAR(30) NOT NULL,CorporationADDRESS VARCHAR(30) NOT NULL,CorporationCITY VARCHAR(30) NOT NULL,CorporationSTATE VARCHAR(30) NOT NULL,CorporationCOUNTRY VARCHAR(30) NOT NULL,CorporationZIPCODE VARCHAR(30) NOT NULL)

