CREATE TABLE Coverage( CoverageID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,CoverageNAME VARCHAR(30) NOT NULL,CoverageADDRESS VARCHAR(30) NOT NULL,CoverageCITY VARCHAR(30) NOT NULL,CoverageSTATE VARCHAR(30) NOT NULL,CoverageCOUNTRY VARCHAR(30) NOT NULL,CoverageZIPCODE VARCHAR(30) NOT NULL)

