CREATE TABLE Currentacount( CurrentacountID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,CurrentacountNAME VARCHAR(30) NOT NULL,CurrentacountADDRESS VARCHAR(30) NOT NULL,CurrentacountCITY VARCHAR(30) NOT NULL,CurrentacountSTATE VARCHAR(30) NOT NULL,CurrentacountCOUNTRY VARCHAR(30) NOT NULL,CurrentacountZIPCODE VARCHAR(30) NOT NULL)

