CREATE TABLE Customer( CustomerID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,CustomerNAME VARCHAR(30) NOT NULL,CustomerADDRESS VARCHAR(30) NOT NULL,CustomerCITY VARCHAR(30) NOT NULL,CustomerSTATE VARCHAR(30) NOT NULL,CustomerCOUNTRY VARCHAR(30) NOT NULL,CustomerZIPCODE VARCHAR(30) NOT NULL)

