CREATE TABLE Department( DepartmentID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,DepartmentNAME VARCHAR(30) NOT NULL,DepartmentADDRESS VARCHAR(30) NOT NULL,DepartmentCITY VARCHAR(30) NOT NULL,DepartmentSTATE VARCHAR(30) NOT NULL,DepartmentCOUNTRY VARCHAR(30) NOT NULL,DepartmentZIPCODE VARCHAR(30) NOT NULL)

