CREATE TABLE Employee( EmployeeID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,EmployeeNAME VARCHAR(30) NOT NULL,EmployeeADDRESS VARCHAR(30) NOT NULL,EmployeeCITY VARCHAR(30) NOT NULL,EmployeeSTATE VARCHAR(30) NOT NULL,EmployeeCOUNTRY VARCHAR(30) NOT NULL,EmployeeZIPCODE VARCHAR(30) NOT NULL)

