CREATE TABLE CUSTOMER( CUSTOMERID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,CUSTOMERNAME VARCHAR(30) NOT NULL,CUSTOMERADDRESS VARCHAR(30) NOT NULL,CUSTOMERCITY VARCHAR(30) NOT NULL,CUSTOMERSTATE VARCHAR(30) NOT NULL,CUSTOMERCOUNTRY VARCHAR(30) NOT NULL,CUSTOMERZIPCODE VARCHAR(30) NOT NULL)

