CREATE TABLE Entitlement( EntitlementID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,EntitlementNAME VARCHAR(30) NOT NULL,EntitlementADDRESS VARCHAR(30) NOT NULL,EntitlementCITY VARCHAR(30) NOT NULL,EntitlementSTATE VARCHAR(30) NOT NULL,EntitlementCOUNTRY VARCHAR(30) NOT NULL,EntitlementZIPCODE VARCHAR(30) NOT NULL)

