CREATE TABLE Equipment( EquipmentID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,EquipmentNAME VARCHAR(30) NOT NULL,EquipmentADDRESS VARCHAR(30) NOT NULL,EquipmentCITY VARCHAR(30) NOT NULL,EquipmentSTATE VARCHAR(30) NOT NULL,EquipmentCOUNTRY VARCHAR(30) NOT NULL,EquipmentZIPCODE VARCHAR(30) NOT NULL)

