CREATE TABLE Estate( EstateID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,EstateNAME VARCHAR(30) NOT NULL,EstateADDRESS VARCHAR(30) NOT NULL,EstateCITY VARCHAR(30) NOT NULL,EstateSTATE VARCHAR(30) NOT NULL,EstateCOUNTRY VARCHAR(30) NOT NULL,EstateZIPCODE VARCHAR(30) NOT NULL)

