CREATE TABLE Event( EventID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,EventNAME VARCHAR(30) NOT NULL,EventADDRESS VARCHAR(30) NOT NULL,EventCITY VARCHAR(30) NOT NULL,EventSTATE VARCHAR(30) NOT NULL,EventCOUNTRY VARCHAR(30) NOT NULL,EventZIPCODE VARCHAR(30) NOT NULL)

