CREATE TABLE Exchangebill( ExchangebillID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,ExchangebillNAME VARCHAR(30) NOT NULL,ExchangebillADDRESS VARCHAR(30) NOT NULL,ExchangebillCITY VARCHAR(30) NOT NULL,ExchangebillSTATE VARCHAR(30) NOT NULL,ExchangebillCOUNTRY VARCHAR(30) NOT NULL,ExchangebillZIPCODE VARCHAR(30) NOT NULL)

