CREATE TABLE Facility( FacilityID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,FacilityNAME VARCHAR(30) NOT NULL,FacilityADDRESS VARCHAR(30) NOT NULL,FacilityCITY VARCHAR(30) NOT NULL,FacilitySTATE VARCHAR(30) NOT NULL,FacilityCOUNTRY VARCHAR(30) NOT NULL,FacilityZIPCODE VARCHAR(30) NOT NULL)

