CREATE TABLE Glaccount( GlaccountID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,GlaccountNAME VARCHAR(30) NOT NULL,GlaccountADDRESS VARCHAR(30) NOT NULL,GlaccountCITY VARCHAR(30) NOT NULL,GlaccountSTATE VARCHAR(30) NOT NULL,GlaccountCOUNTRY VARCHAR(30) NOT NULL,GlaccountZIPCODE VARCHAR(30) NOT NULL)

