CREATE TABLE Hospital( HospitalID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,HospitalNAME VARCHAR(30) NOT NULL,HospitalADDRESS VARCHAR(30) NOT NULL,HospitalCITY VARCHAR(30) NOT NULL,HospitalSTATE VARCHAR(30) NOT NULL,HospitalCOUNTRY VARCHAR(30) NOT NULL,HospitalZIPCODE VARCHAR(30) NOT NULL)

