CREATE TABLE House( HouseID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,HouseNAME VARCHAR(30) NOT NULL,HouseADDRESS VARCHAR(30) NOT NULL,HouseCITY VARCHAR(30) NOT NULL,HouseSTATE VARCHAR(30) NOT NULL,HouseCOUNTRY VARCHAR(30) NOT NULL,HouseZIPCODE VARCHAR(30) NOT NULL)

