CREATE TABLE HouseSecurity( HouseSecurityID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,HouseSecurityNAME VARCHAR(30) NOT NULL,HouseSecurityADDRESS VARCHAR(30) NOT NULL,HouseSecurityCITY VARCHAR(30) NOT NULL,HouseSecuritySTATE VARCHAR(30) NOT NULL,HouseSecurityCOUNTRY VARCHAR(30) NOT NULL,HouseSecurityZIPCODE VARCHAR(30) NOT NULL)

