CREATE TABLE HouseAccesory( HouseAccesoryID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,HouseAccesoryNAME VARCHAR(30) NOT NULL,HouseAccesoryADDRESS VARCHAR(30) NOT NULL,HouseAccesoryCITY VARCHAR(30) NOT NULL,HouseAccesorySTATE VARCHAR(30) NOT NULL,HouseAccesoryCOUNTRY VARCHAR(30) NOT NULL,HouseAccesoryZIPCODE VARCHAR(30) NOT NULL)

