CREATE TABLE Invoice( InvoiceID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,InvoiceNAME VARCHAR(30) NOT NULL,InvoiceADDRESS VARCHAR(30) NOT NULL,InvoiceCITY VARCHAR(30) NOT NULL,InvoiceSTATE VARCHAR(30) NOT NULL,InvoiceCOUNTRY VARCHAR(30) NOT NULL,InvoiceZIPCODE VARCHAR(30) NOT NULL)

