CREATE TABLE Lab( LabID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,LabNAME VARCHAR(30) NOT NULL,LabADDRESS VARCHAR(30) NOT NULL,LabCITY VARCHAR(30) NOT NULL,LabSTATE VARCHAR(30) NOT NULL,LabCOUNTRY VARCHAR(30) NOT NULL,LabZIPCODE VARCHAR(30) NOT NULL)

