CREATE TABLE Ledger( LedgerID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,LedgerNAME VARCHAR(30) NOT NULL,LedgerADDRESS VARCHAR(30) NOT NULL,LedgerCITY VARCHAR(30) NOT NULL,LedgerSTATE VARCHAR(30) NOT NULL,LedgerCOUNTRY VARCHAR(30) NOT NULL,LedgerZIPCODE VARCHAR(30) NOT NULL)

