CREATE TABLE Liability( LiabilityID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,LiabilityNAME VARCHAR(30) NOT NULL,LiabilityADDRESS VARCHAR(30) NOT NULL,LiabilityCITY VARCHAR(30) NOT NULL,LiabilitySTATE VARCHAR(30) NOT NULL,LiabilityCOUNTRY VARCHAR(30) NOT NULL,LiabilityZIPCODE VARCHAR(30) NOT NULL)

