CREATE TABLE Loanaccount( LoanaccountID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,LoanaccountNAME VARCHAR(30) NOT NULL,LoanaccountADDRESS VARCHAR(30) NOT NULL,LoanaccountCITY VARCHAR(30) NOT NULL,LoanaccountSTATE VARCHAR(30) NOT NULL,LoanaccountCOUNTRY VARCHAR(30) NOT NULL,LoanaccountZIPCODE VARCHAR(30) NOT NULL)

