CREATE TABLE Loan( LoanID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,LoanNAME VARCHAR(30) NOT NULL,LoanADDRESS VARCHAR(30) NOT NULL,LoanCITY VARCHAR(30) NOT NULL,LoanSTATE VARCHAR(30) NOT NULL,LoanCOUNTRY VARCHAR(30) NOT NULL,LoanZIPCODE VARCHAR(30) NOT NULL)

