CREATE TABLE Location( LocationID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,LocationNAME VARCHAR(30) NOT NULL,LocationADDRESS VARCHAR(30) NOT NULL,LocationCITY VARCHAR(30) NOT NULL,LocationSTATE VARCHAR(30) NOT NULL,LocationCOUNTRY VARCHAR(30) NOT NULL,LocationZIPCODE VARCHAR(30) NOT NULL)

