CREATE TABLE Organization( OrganizationID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,OrganizationNAME VARCHAR(30) NOT NULL,OrganizationADDRESS VARCHAR(30) NOT NULL,OrganizationCITY VARCHAR(30) NOT NULL,OrganizationSTATE VARCHAR(30) NOT NULL,OrganizationCOUNTRY VARCHAR(30) NOT NULL,OrganizationZIPCODE VARCHAR(30) NOT NULL)

