CREATE TABLE Owner( OwnerID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,OwnerNAME VARCHAR(30) NOT NULL,OwnerADDRESS VARCHAR(30) NOT NULL,OwnerCITY VARCHAR(30) NOT NULL,OwnerSTATE VARCHAR(30) NOT NULL,OwnerCOUNTRY VARCHAR(30) NOT NULL,OwnerZIPCODE VARCHAR(30) NOT NULL)

