CREATE TABLE Partner( PartnerID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,PartnerNAME VARCHAR(30) NOT NULL,PartnerADDRESS VARCHAR(30) NOT NULL,PartnerCITY VARCHAR(30) NOT NULL,PartnerSTATE VARCHAR(30) NOT NULL,PartnerCOUNTRY VARCHAR(30) NOT NULL,PartnerZIPCODE VARCHAR(30) NOT NULL)

