CREATE TABLE Patient( PatientID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,PatientNAME VARCHAR(30) NOT NULL,PatientADDRESS VARCHAR(30) NOT NULL,PatientCITY VARCHAR(30) NOT NULL,PatientSTATE VARCHAR(30) NOT NULL,PatientCOUNTRY VARCHAR(30) NOT NULL,PatientZIPCODE VARCHAR(30) NOT NULL)

