CREATE TABLE Payable( PayableID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,PayableNAME VARCHAR(30) NOT NULL,PayableADDRESS VARCHAR(30) NOT NULL,PayableCITY VARCHAR(30) NOT NULL,PayableSTATE VARCHAR(30) NOT NULL,PayableCOUNTRY VARCHAR(30) NOT NULL,PayableZIPCODE VARCHAR(30) NOT NULL)

