CREATE TABLE Payment( PaymentID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,PaymentNAME VARCHAR(30) NOT NULL,PaymentADDRESS VARCHAR(30) NOT NULL,PaymentCITY VARCHAR(30) NOT NULL,PaymentSTATE VARCHAR(30) NOT NULL,PaymentCOUNTRY VARCHAR(30) NOT NULL,PaymentZIPCODE VARCHAR(30) NOT NULL)

