CREATE TABLE Person( PersonID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,PersonNAME VARCHAR(30) NOT NULL,PersonADDRESS VARCHAR(30) NOT NULL,PersonCITY VARCHAR(30) NOT NULL,PersonSTATE VARCHAR(30) NOT NULL,PersonCOUNTRY VARCHAR(30) NOT NULL,PersonZIPCODE VARCHAR(30) NOT NULL)

