CREATE TABLE Portfolio( PortfolioID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,PortfolioNAME VARCHAR(30) NOT NULL,PortfolioADDRESS VARCHAR(30) NOT NULL,PortfolioCITY VARCHAR(30) NOT NULL,PortfolioSTATE VARCHAR(30) NOT NULL,PortfolioCOUNTRY VARCHAR(30) NOT NULL,PortfolioZIPCODE VARCHAR(30) NOT NULL)

