CREATE TABLE Position( PositionID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,PositionNAME VARCHAR(30) NOT NULL,PositionADDRESS VARCHAR(30) NOT NULL,PositionCITY VARCHAR(30) NOT NULL,PositionSTATE VARCHAR(30) NOT NULL,PositionCOUNTRY VARCHAR(30) NOT NULL,PositionZIPCODE VARCHAR(30) NOT NULL)

