CREATE TABLE Practitioner( PractitionerID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,PractitionerNAME VARCHAR(30) NOT NULL,PractitionerADDRESS VARCHAR(30) NOT NULL,PractitionerCITY VARCHAR(30) NOT NULL,PractitionerSTATE VARCHAR(30) NOT NULL,PractitionerCOUNTRY VARCHAR(30) NOT NULL,PractitionerZIPCODE VARCHAR(30) NOT NULL)

