CREATE TABLE Product( ProductID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,ProductNAME VARCHAR(30) NOT NULL,ProductADDRESS VARCHAR(30) NOT NULL,ProductCITY VARCHAR(30) NOT NULL,ProductSTATE VARCHAR(30) NOT NULL,ProductCOUNTRY VARCHAR(30) NOT NULL,ProductZIPCODE VARCHAR(30) NOT NULL)

