CREATE TABLE Project( ProjectID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,ProjectNAME VARCHAR(30) NOT NULL,ProjectADDRESS VARCHAR(30) NOT NULL,ProjectCITY VARCHAR(30) NOT NULL,ProjectSTATE VARCHAR(30) NOT NULL,ProjectCOUNTRY VARCHAR(30) NOT NULL,ProjectZIPCODE VARCHAR(30) NOT NULL)

