CREATE TABLE PropertyInsurer( PropertyInsurerID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,PropertyInsurerNAME VARCHAR(30) NOT NULL,PropertyInsurerADDRESS VARCHAR(30) NOT NULL,PropertyInsurerCITY VARCHAR(30) NOT NULL,PropertyInsurerSTATE VARCHAR(30) NOT NULL,PropertyInsurerCOUNTRY VARCHAR(30) NOT NULL,PropertyInsurerZIPCODE VARCHAR(30) NOT NULL)

