CREATE TABLE Provider( ProviderID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,ProviderNAME VARCHAR(30) NOT NULL,ProviderADDRESS VARCHAR(30) NOT NULL,ProviderCITY VARCHAR(30) NOT NULL,ProviderSTATE VARCHAR(30) NOT NULL,ProviderCOUNTRY VARCHAR(30) NOT NULL,ProviderZIPCODE VARCHAR(30) NOT NULL)

