CREATE TABLE Resource( ResourceID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,ResourceNAME VARCHAR(30) NOT NULL,ResourceADDRESS VARCHAR(30) NOT NULL,ResourceCITY VARCHAR(30) NOT NULL,ResourceSTATE VARCHAR(30) NOT NULL,ResourceCOUNTRY VARCHAR(30) NOT NULL,ResourceZIPCODE VARCHAR(30) NOT NULL)

