CREATE TABLE Savingsaccount( SavingsaccountID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,SavingsaccountNAME VARCHAR(30) NOT NULL,SavingsaccountADDRESS VARCHAR(30) NOT NULL,SavingsaccountCITY VARCHAR(30) NOT NULL,SavingsaccountSTATE VARCHAR(30) NOT NULL,SavingsaccountCOUNTRY VARCHAR(30) NOT NULL,SavingsaccountZIPCODE VARCHAR(30) NOT NULL)

