CREATE TABLE Schedule( ScheduleID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,ScheduleNAME VARCHAR(30) NOT NULL,ScheduleADDRESS VARCHAR(30) NOT NULL,ScheduleCITY VARCHAR(30) NOT NULL,ScheduleSTATE VARCHAR(30) NOT NULL,ScheduleCOUNTRY VARCHAR(30) NOT NULL,ScheduleZIPCODE VARCHAR(30) NOT NULL)

