CREATE TABLE Settlement( SettlementID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,SettlementNAME VARCHAR(30) NOT NULL,SettlementADDRESS VARCHAR(30) NOT NULL,SettlementCITY VARCHAR(30) NOT NULL,SettlementSTATE VARCHAR(30) NOT NULL,SettlementCOUNTRY VARCHAR(30) NOT NULL,SettlementZIPCODE VARCHAR(30) NOT NULL)

