CREATE TABLE Shippingpoint( ShippingpointID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,ShippingpointNAME VARCHAR(30) NOT NULL,ShippingpointADDRESS VARCHAR(30) NOT NULL,ShippingpointCITY VARCHAR(30) NOT NULL,ShippingpointSTATE VARCHAR(30) NOT NULL,ShippingpointCOUNTRY VARCHAR(30) NOT NULL,ShippingpointZIPCODE VARCHAR(30) NOT NULL)

