CREATE TABLE Store( StoreID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,StoreNAME VARCHAR(30) NOT NULL,StoreADDRESS VARCHAR(30) NOT NULL,StoreCITY VARCHAR(30) NOT NULL,StoreSTATE VARCHAR(30) NOT NULL,StoreCOUNTRY VARCHAR(30) NOT NULL,StoreZIPCODE VARCHAR(30) NOT NULL)

