CREATE TABLE Supplier( SupplierID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,SupplierNAME VARCHAR(30) NOT NULL,SupplierADDRESS VARCHAR(30) NOT NULL,SupplierCITY VARCHAR(30) NOT NULL,SupplierSTATE VARCHAR(30) NOT NULL,SupplierCOUNTRY VARCHAR(30) NOT NULL,SupplierZIPCODE VARCHAR(30) NOT NULL)

