CREATE TABLE Transaction( TransactionID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,TransactionNAME VARCHAR(30) NOT NULL,TransactionADDRESS VARCHAR(30) NOT NULL,TransactionCITY VARCHAR(30) NOT NULL,TransactionSTATE VARCHAR(30) NOT NULL,TransactionCOUNTRY VARCHAR(30) NOT NULL,TransactionZIPCODE VARCHAR(30) NOT NULL)

