CREATE TABLE Vendor( VendorID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,VendorNAME VARCHAR(30) NOT NULL,VendorADDRESS VARCHAR(30) NOT NULL,VendorCITY VARCHAR(30) NOT NULL,VendorSTATE VARCHAR(30) NOT NULL,VendorCOUNTRY VARCHAR(30) NOT NULL,VendorZIPCODE VARCHAR(30) NOT NULL)

