CREATE TABLE Warehouse( WarehouseID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,WarehouseNAME VARCHAR(30) NOT NULL,WarehouseADDRESS VARCHAR(30) NOT NULL,WarehouseCITY VARCHAR(30) NOT NULL,WarehouseSTATE VARCHAR(30) NOT NULL,WarehouseCOUNTRY VARCHAR(30) NOT NULL,WarehouseZIPCODE VARCHAR(30) NOT NULL)

